<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Arsip_model extends CI_Model
{

    public $table = 'arsip';
    public $id = 'id_arsip';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_arsip,pbr_nama,pnr_nama,nama_arsip,link_arsip,tgl_input_arsip');
        $this->datatables->from('arsip');
        //add this line for join
        $this->datatables->join('pbr_fidusia', 'arsip.id_pbr_fidusia = pbr_fidusia.id_pbr_fidusia');
        $this->datatables->join('pnr_fidusia', 'arsip.id_pnr_fidusia = pnr_fidusia.id_pnr_fidusia');
        $this->datatables->add_column('action', anchor(site_url('arsip/read/$1'),'Read')." | ".anchor(site_url('arsip/update/$1'),'Update')." | ".anchor(site_url('arsip/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_arsip');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->like('id_arsip', $q);
	$this->db->or_like('id_pbr_fidusia', $q);
	$this->db->or_like('id_pnr_fidusia', $q);
	$this->db->or_like('nama_arsip', $q);
	$this->db->or_like('link_arsip', $q);
	$this->db->or_like('tgl_input_arsip', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_arsip', $q);
	$this->db->or_like('id_pbr_fidusia', $q);
	$this->db->or_like('id_pnr_fidusia', $q);
	$this->db->or_like('nama_arsip', $q);
	$this->db->or_like('link_arsip', $q);
	$this->db->or_like('tgl_input_arsip', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
	
    function AllPbr()
    {
        
        $query = $this->db->get('pbr_fidusia');
		/*
        foreach ($query->result() as $row)
        {
            echo $row->description;
        }*/

		//$query = $this->db->get_where('pbr_fidusia',array('role'=>'User'));
        return $query->result();

        //echo 'Total Results: ' . $query->num_rows();
    }
	
    function AllPnr()
    {
        
        $query = $this->db->get('pnr_fidusia');
		/*
        foreach ($query->result() as $row)
        {
            echo $row->description;
        }*/

		//$query = $this->db->get_where('pbr_fidusia',array('role'=>'User'));
        return $query->result();

        //echo 'Total Results: ' . $query->num_rows();
    }

}

/* End of file Arsip_model.php */
/* Location: ./application/models/Arsip_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-28 19:44:37 */
/* http://harviacode.com */