<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pbr_fidusia_model extends CI_Model
{

    public $table = 'pbr_fidusia';
    public $id = 'id_pbr_fidusia';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_pbr_fidusia,id,pbr_nama,pbr_alamat,pbr_nik,pbr_jengkel,pbr_nmr_kontak');
        $this->datatables->from('pbr_fidusia');
        //add this line for join
        //$this->datatables->join('user', 'pbr_fidusia.id = user.id');
        $this->datatables->add_column('action', anchor(site_url('pbr_fidusia/read/$1'),'Read')." | ".anchor(site_url('pbr_fidusia/update/$1'),'Update')." | ".anchor(site_url('pbr_fidusia/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_pbr_fidusia');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pbr_fidusia', $q);
	$this->db->or_like('id', $q);
	$this->db->or_like('pbr_nama', $q);
	$this->db->or_like('pbr_alamat', $q);
	$this->db->or_like('pbr_nik', $q);
	$this->db->or_like('pbr_jengkel', $q);
	$this->db->or_like('pbr_nmr_kontak', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pbr_fidusia', $q);
	$this->db->or_like('id', $q);
	$this->db->or_like('pbr_nama', $q);
	$this->db->or_like('pbr_alamat', $q);
	$this->db->or_like('pbr_nik', $q);
	$this->db->or_like('pbr_jengkel', $q);
	$this->db->or_like('pbr_nmr_kontak', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getAllGroups()
    {
        /*
        $query = $this->db->get('location');

        foreach ($query->result() as $row)
        {
            echo $row->description;
        }*/

		$query = $this->db->get_where('user',array('role'=>'User'));
        return $query->result();

        //echo 'Total Results: ' . $query->num_rows();
    }

}

/* End of file Pbr_fidusia_model.php */
/* Location: ./application/models/Pbr_fidusia_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-28 15:50:58 */
/* http://harviacode.com */