<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Progress_model extends CI_Model
{

    public $table = 'progress';
    public $id = 'id_pjm_fidusia';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('progress.id_pjm_fidusia,nama_user,status,pbr_nama,pnr_nama,progress.tanggal_buat');
        $this->datatables->from('progress');
        $this->datatables->join('user', 'progress.id = user.id');
        $this->datatables->join('pjm_fidusia', 'progress.id_pjm_fidusia = pjm_fidusia.id_pjm_fidusia');
        $this->datatables->join('pbr_fidusia', 'progress.id_pbr_fidusia = pbr_fidusia.id_pbr_fidusia');
        $this->datatables->join('pnr_fidusia', 'progress.id_pnr_fidusia = pnr_fidusia.id_pnr_fidusia');
        $this->datatables->add_column('action', anchor(site_url('progress/read/$1'),'Read')." | ".anchor(site_url('progress/update/$1'),'Update')." | ".anchor(site_url('progress/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_progress');
        return $this->datatables->generate();
    }
	
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
	$this->db->or_like('id', $q);
	$this->db->or_like('id_pjm_fidusia', $q);
	$this->db->or_like('id_pbr_fidusia', $q);
	$this->db->or_like('id_pnr_fidusia', $q);
	$this->db->or_like('tanggal_buat', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
	$this->db->or_like('id', $q);
	$this->db->or_like('id_pjm_fidusia', $q);
	$this->db->or_like('id_pbr_fidusia', $q);
	$this->db->or_like('id_pnr_fidusia', $q);
	$this->db->or_like('tanggal_buat', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

 	function kode_otomatis_progress(){
 		$this->db->select('right(id_pjm_fidusia ,4) as kode', false);
 		$this->db->order_by('id_pjm_fidusia' ,'desc');
 		$this->db->limit(100);
 		$query=$this->db->get('progress');
 		if($query->num_rows()<>0){
 			$data=$query->row();
 			$kode=intval($data->kode)+1;
 		}else{
 			$kode=1;
 		}

 		$kodemax=str_pad($kode,4,"0", STR_PAD_LEFT);
 		$kodejadi='PJMF'.$kodemax;

 		return $kodejadi;
 	}

	function edit_data($where,$table){
		return $this->db->get_where($table,$where);
 	}
	
 	function delete_data($where,$table){
 		$this->db->where($where);
 		$this->db->delete($table);
 	}
	
	function find($where,$table){
		//query mencari record berdasarkan ID-nya
		$hasil=$this->db->where('id_pjm_fidusia',$where)
					->limit(100)
					->get($table);
		if($hasil->num_rows()<>0){
			return $hasil->row();
		}else{
			return array();
			}
	}

}


/* End of file Progress_model.php */
/* Location: ./application/models/Progress_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-05 18:33:11 */
/* http://harviacode.com */